# PostgreSQL Configuration for local development
# spring.application.name=spirited-hub
# spring.datasource.url=jdbc:postgresql://localhost:5432/spirited_hub_db
# spring.datasource.username=postgres
# spring.datasource.password=akram123
# spring.datasource.driver-class-name=org.postgresql.Driver
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true


# MySQL Configuration for local development
# spring.application.name=spirited-hub
# spring.datasource.url=jdbc:mysql://shuttle.proxy.rlwy.net:56033/railway
# spring.datasource.username=root
# spring.datasource.password=JfBQtbNfQKtCElCESiQgIEaswjtWBari
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true


# H2 Database Configuration for local testing
# spring.datasource.url=jdbc:h2:mem:testdb
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# spring.h2.console.enabled=true

# Server Configuration
# server.port=${PORT:8080}
# server.address=0.0.0.0

# Spring Mail Configuration for Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=akram97051@gmail.com
spring.mail.password=kweqkksnezwpfagy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.test-connection=true

# =========================
# Application Name
# =========================
spring.application.name=spirited-hub

# =========================
# MySQL Configuration
# =========================
# MySQL configuration from Railway
spring.datasource.url=jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQL_DATABASE}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server configuration
server.port=${PORT:8080}
server.address=0.0.0.0